### ISSUE TITLE
Workflow is simply named "main" in .dockstore.yml

### ISSUE THREAD

**Issue by fbacall** [iwc-workflows/parallel-accession-download#1]
https://github.com/iwc-workflows/parallel-accession-download/blob/main/.dockstore.yml#L3

This leads to the scraped workflow being titled "main" on WorkflowHub: https://workflowhub.eu/workflows/137

Should probably be changed to something more descriptive.

**Comment by mvdbeek** [comment]
No, this is the main workflow. The workflow name is parallel-accession-download, and the TRS id is `#workflow/github.com/iwc-workflows/parallel-accession-download/main`

**Comment by fbacall** [comment]
OK... I'll change the WorkflowHub scraper to use the repo name for the workflow title.

**Comment by mvdbeek** [comment]
Thank you!

**Comment by mvdbeek** [comment]
Wait -- that's not right either for multiple workflows in a repository. Can you make the name `parallel-accession-download/main` or generally `repo-name/workflow-name` ?

**Comment by simleo** [comment]
The workflow name as listed in `parallel-accession-download.ga` is "Parallel Accession Download", and that's what I've been putting into the RO-Crate metadata so far (that's what WorkflowHub picks up when the crate is uploaded via the API). OTOH, "main" only appears in `.dockstore.yml`. So we're moving to `repo-name/dockstore-workflow-name` I guess.

However, WorkflowHub requires the presence of a _main workflow_ in the crate, while Dockstore supports an array of equally important workflows, each resulting in a separate Dockstore entry. Right now there's only one workflow in each repo, but if multiple workflows per repo are expected in the future we should work out how to handle them.
